import type { Creator, NotificationItem, PromptPost } from './types'

export const creators: Creator[] = [
  { id: 'c1', username: 'aiexplorer', name: 'AI Explorer', avatar: 'AE', bio: 'Exploring practical prompts for visual creators.', followers: 3240, following: 118, posts: 84 },
  { id: 'c2', username: 'pixelwizard', name: 'Pixel Wizard', avatar: 'PW', bio: 'Creative direction, portraits and cinematic worlds.', followers: 8120, following: 240, posts: 132 },
  { id: 'c3', username: 'digitaldreamer', name: 'Digital Dreamer', avatar: 'DD', bio: 'Turning ideas into visual stories.', followers: 5230, following: 96, posts: 61 },
  { id: 'c4', username: 'naturelover', name: 'Nature Lover', avatar: 'NL', bio: 'Landscape prompts and outdoor visual studies.', followers: 1980, following: 74, posts: 47 },
]

const longPrompt = 'Transform the supplied image into a cinematic editorial photograph with natural skin texture, realistic proportions, subtle film grain, soft directional lighting, rich but believable colors, controlled highlights, deep shadows, authentic lens depth, and a premium DSLR look. Preserve the identity, clothing, subject geometry and environment while improving composition and visual clarity.'

export const demoPosts: PromptPost[] = [
  { id: 'p1', title: 'Cinematic Portrait Upgrade', description: 'A natural editorial finish without changing identity.', before: '/demo-before.svg', after: '/demo-portrait.svg', prompt: longPrompt, negativePrompt: 'plastic skin, face reshaping, over-sharpening, artificial HDR, extra fingers', tool: 'ChatGPT', model: 'GPT Image', category: 'Portrait', tags: ['cinematic', 'portrait', 'dslr', 'natural'], likes: 248, saves: 86, copies: 426, views: 1284, comments: 32, remixes: 18, createdAt: '2h ago', creator: creators[0] },
  { id: 'p2', title: 'Dreamy Mountain Landscape', description: 'Turn a flat landscape into a rich cinematic travel frame.', before: '/demo-before.svg', after: '/demo-landscape.svg', prompt: 'Enhance this landscape with vibrant but natural colors, golden-hour light, realistic atmospheric depth, detailed mountains, cinematic contrast, and a premium travel-photography finish. Preserve the original composition and natural geography.', tool: 'Gemini', model: 'Imagen', category: 'Landscape', tags: ['landscape', 'travel', 'nature', 'golden-hour'], likes: 756, saves: 210, copies: 612, views: 3240, comments: 76, remixes: 44, createdAt: '5h ago', creator: creators[3] },
  { id: 'p3', title: 'Neon Creative Portrait', description: 'Moody studio portrait with controlled neon accents.', before: '/demo-before.svg', after: '/demo-portrait.svg', prompt: 'Create a premium studio portrait with subtle cyan and violet neon rim lighting, realistic skin texture, soft shadows, shallow depth of field, clean background separation and an authentic mirrorless-camera finish. Keep the person recognizable and natural.', tool: 'Midjourney', model: 'V7', category: 'Photography', tags: ['neon', 'portrait', 'studio', 'creative'], likes: 1200, saves: 388, copies: 944, views: 8420, comments: 145, remixes: 72, createdAt: '1d ago', creator: creators[2] },
  { id: 'p4', title: 'Premium Product Scene', description: 'Clean product hero image for modern brands.', before: '/demo-before.svg', after: '/demo-product.svg', prompt: 'Create a clean premium product photograph with soft studio lighting, subtle cyan-violet gradient ambience, realistic materials, controlled reflections, elegant negative space and crisp but natural detail. Keep the product shape exact.', tool: 'Flux', model: 'Flux 1.1 Pro', category: 'Product', tags: ['product', 'commercial', 'studio', 'branding'], likes: 642, saves: 294, copies: 721, views: 6190, comments: 58, remixes: 39, createdAt: '2d ago', creator: creators[1] },
  { id: 'p5', title: 'Natural Color Restoration', description: 'Bring life back to a dull photo while keeping it believable.', before: '/demo-before.svg', after: '/demo-landscape.svg', prompt: 'Restore the image with balanced exposure, natural white balance, subtle color richness, realistic shadows and highlights, fine detail, and a professional camera color grade. Do not change faces, objects, proportions or the original setting.', tool: 'ChatGPT', model: 'GPT Image', category: 'Photography', tags: ['restoration', 'color', 'photo-edit', 'natural'], likes: 512, saves: 168, copies: 508, views: 2710, comments: 41, remixes: 21, createdAt: '3d ago', creator: creators[1] },
  { id: 'p6', title: 'Fantasy World Builder', description: 'A reusable template for cinematic fantasy scenes.', before: '/demo-landscape.svg', after: '/demo-portrait.svg', prompt: 'Turn the supplied scene into an immersive cinematic fantasy world while preserving the main subject and perspective. Add believable environmental storytelling, atmospheric depth, soft volumetric light, rich textures and a cohesive color palette. Keep the result photorealistic.', tool: 'Leonardo AI', model: 'Phoenix', category: 'Art', tags: ['fantasy', 'worldbuilding', 'cinematic', 'concept'], likes: 391, saves: 231, copies: 824, views: 4820, comments: 64, remixes: 53, createdAt: '4d ago', creator: creators[2] },
]

export const demoNotifications: NotificationItem[] = [
  { id: 'n1', type: 'copy', text: 'Your “Cinematic Portrait Upgrade” reached 400 prompt copies.', time: '12 min ago', read: false },
  { id: 'n2', type: 'like', text: 'Pixel Wizard liked your latest prompt.', time: '1h ago', read: false },
  { id: 'n3', type: 'remix', text: 'John remixed your prompt “Natural Color Restoration”.', time: '3h ago', read: true },
  { id: 'n4', type: 'follow', text: 'Nature Lover started following you.', time: 'Yesterday', read: true },
]
